language: rust

os: osx
osx_image: xcode10.1
addons:
  homebrew:
    packages:
      - bats-core
rust:
  - stable
#  - 1.28.0
  - beta
#  - nightly

stages:
  - check
  - test

jobs:
  include:
    - stage: check
      os: linux
      dist: xenial
      rust: stable
      before_script:
        - rustup component add rustfmt clippy
      script:
        - (cd . && cargo fmt --all -- --check)
        - (cd ./testdata/simple && cargo fmt --all -- --check)
        - (cd ./testdata/workspace && cargo fmt --all -- --check)
        - cargo clippy --all --manifest-path ./Cargo.toml -- --deny warnings
        - cargo clippy --all --manifest-path ./testdata/simple/Cargo.toml -- --deny warnings
        - cargo clippy --all --manifest-path ./testdata/workspace/Cargo.toml -- --deny warnings

before_script:
  - rustup target add aarch64-apple-ios x86_64-apple-ios

script:
  - set -e
  - cargo build
  - export PATH="$PWD/target/debug:$PATH"
  - cargo lipo --version
  - ./integration.bats.sh --pretty
